# Form implementation generated from reading ui file 'E:\PycharmProjects\K24406H\DO_AN_NHOM_KTLT\ui\BookingApp.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import DO_AN_NHOM_KTLT.ui.booking_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 591)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-image: url(:/images/images/abc2.jpg);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat; \n"
"}\n"
"/* Chỉnh màu cho QPushButton */\n"
"QPushButton {\n"
"    background-color: #FFB703; /* Cam nhạt để hợp với xanh lá */\n"
"    color: white;\n"
"    font-size: 16px;  /* Tăng kích thước chữ */\n"
"    font-weight: bold;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E85D04; /* Cam đậm khi hover */\n"
"}\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #114514; \n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 120, 511, 311))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgba(255, 255, 255, 180); \n"
"    border: 2px solid white; \n"
"    border-radius: 20px; \n"
"    padding: 10px;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 10px;\n"
"    font-weight: bold;\n"
"    font-size: 22px;\n"
"    color: black;\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 181, 31))
        self.label_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 181, 41))
        self.label_5.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 151, 31))
        self.label_6.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 151, 31))
        self.label_7.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.lineEditTenKH = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditTenKH.setGeometry(QtCore.QRect(200, 40, 271, 41))
        self.lineEditTenKH.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 200);\n"
"    border: 1.5px solid white;\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"    color: black;\n"
"}\n"
"")
        self.lineEditTenKH.setObjectName("lineEditTenKH")
        self.lineEditSDT = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditSDT.setGeometry(QtCore.QRect(200, 90, 271, 41))
        self.lineEditSDT.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 200);\n"
"    border: 1.5px solid white;\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"    color: black;\n"
"}\n"
"")
        self.lineEditSDT.setObjectName("lineEditSDT")
        self.lineEditCCCD = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditCCCD.setGeometry(QtCore.QRect(200, 140, 271, 41))
        self.lineEditCCCD.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 200);\n"
"    border: 1.5px solid white;\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"    color: black;\n"
"}\n"
"")
        self.lineEditCCCD.setObjectName("lineEditCCCD")
        self.lineEditSTTP = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditSTTP.setGeometry(QtCore.QRect(200, 190, 271, 41))
        self.lineEditSTTP.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 200);\n"
"    border: 1.5px solid white;\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"    color: black;\n"
"}")
        self.lineEditSTTP.setObjectName("lineEditSTTP")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 240, 191, 41))
        self.label_11.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.groupBox)
        self.dateTimeEdit.setGeometry(QtCore.QRect(200, 240, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setStyleSheet("QDateTimeEdit {\n"
"    background-color: rgba(255, 255, 255, 200);\n"
"    border: 1.5px solid white;\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"    color: black;\n"
"}\n"
"QDateTimeEdit::up-button, QDateTimeEdit::down-button {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"/* Tạo mũi tên nhỏ hơn */\n"
"QDateTimeEdit::up-arrow, QDateTimeEdit::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}")
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(550, 120, 631, 311))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgba(255, 255, 255, 180); \n"
"    border: 2px solid white; \n"
"    border-radius: 20px; \n"
"    padding: 10px;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 10px;\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"}\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.groupBox_2)
        self.tableWidget.setGeometry(QtCore.QRect(20, 40, 601, 250))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 250))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: rgba(255, 255, 255, 200);\n"
"    border-radius: 15px;\n"
"}\n"
"QHeaderView::section {\n"
"    font-weight: bold;\n"
"    padding: 6px;\n"
"    border: none;\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.pushButtonBook = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBook.setGeometry(QtCore.QRect(150, 470, 221, 71))
        self.pushButtonBook.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 160);\n"
"    border: 2px solid white;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #114514;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 220);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.pushButtonBook.setObjectName("pushButtonBook")
        self.pushButtonNew = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonNew.setGeometry(QtCore.QRect(490, 470, 221, 71))
        self.pushButtonNew.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 160);\n"
"    border: 2px solid white;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #114514;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 220);\n"
"}\n"
"")
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(840, 470, 221, 71))
        self.pushButtonExit.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 160);\n"
"    border: 2px solid white;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #114514;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 220);\n"
"}\n"
"")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 30, 401, 61))
        self.label.setStyleSheet("QLabel {\n"
"    font-family: \'Montserrat\', sans-serif;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    color: #FFFFFF; \n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BookingApp"))
        self.groupBox.setTitle(_translate("MainWindow", "Vui lòng nhập các thông tin sau:"))
        self.label_3.setText(_translate("MainWindow", "Tên khách hàng:"))
        self.label_5.setText(_translate("MainWindow", "Số điện thoại:"))
        self.label_6.setText(_translate("MainWindow", "CCCD:"))
        self.label_7.setText(_translate("MainWindow", "Phòng:"))
        self.label_11.setText(_translate("MainWindow", "Ngày nhận phòng:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Danh sách phòng trống:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT Phòng"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Loại phòng"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Giá/giờ"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Giá/đêm"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Trạng thái"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Tầng"))
        self.pushButtonBook.setText(_translate("MainWindow", "Đặt phòng"))
        self.pushButtonNew.setText(_translate("MainWindow", "Tạo mới"))
        self.pushButtonExit.setText(_translate("MainWindow", "Thoát"))
        self.label.setText(_translate("MainWindow", "QUẢN LÝ ĐẶT PHÒNG"))
