# Form implementation generated from reading ui file 'E:\PycharmProjects\K24406H\DO_AN_NHOM_KTLT\ui\LoginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import DO_AN_NHOM_KTLT.ui.resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 470)
        MainWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-image: url(:/images/images/ic_hotel.jpg);\n"
"    background-repeat: no-repeat;\n"
"    background-size: cover;\n"
"}\n"
"QPushButton {\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-size: 12px; /* Giảm size chữ */\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: #2E5636;\n"
"    border: 2px solid #1E3E26;\n"
"    border-radius: 12px; /* Giảm độ bo góc */\n"
"    padding: 5px 15px; /* Giảm padding để nút nhỏ hơn */\n"
"    min-width: 50px; /* Giảm kích thước tối thiểu của nút */\n"
"    transition: background 0.3s ease-in-out, transform 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1E3E26;\n"
"    transform: scale(1.05);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #153021;\n"
"    transform: scale(0.95);\n"
"}\n"
"QLabel {\n"
"    color: #2E5636; /* Xanh lá đậm hơn */\n"
"    background: transparent;\n"
"    font-size: 12px;\n"
"    font-weight: normal;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(150, 30, 331, 401))
        font = QtGui.QFont()
        font.setKerning(True)
        self.frame.setFont(font)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgba(255, 255, 255, 0.4); /* Nền trắng mờ */\n"
"    border: none; /* Không viền hoặc có thể thêm viền nhẹ */\n"
"    border-radius: 15px; /* Bo góc mềm mại */\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setObjectName("frame")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditPassword.setGeometry(QtCore.QRect(100, 200, 201, 31))
        self.lineEditPassword.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0.8); /* Nền trắng rõ hơn */\n"
"    border: 2px solid rgba(255, 255, 255, 1); /* Viền trắng đậm */\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-size: 12px;\n"
"    color: black;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgba(0, 0, 0, 0.7); /* Viền đen khi nhập */\n"
"    background-color: rgba(255, 255, 255, 1); /* Sáng hơn khi nhập */\n"
"}\n"
"")
        self.lineEditPassword.setText("")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonLogin.setGeometry(QtCore.QRect(30, 300, 121, 41))
        self.pushButtonLogin.setStyleSheet("QPushButton {\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-size: 14px; /* Giảm size chữ */\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: #2E5636;\n"
"    border: 2px solid #1E3E26;\n"
"    border-radius: 12px; /* Giảm độ bo góc */\n"
"    padding: 5px 15px; /* Giảm padding để nút nhỏ hơn */\n"
"    min-width: 80px; /* Giảm kích thước tối thiểu của nút */\n"
"    transition: background 0.3s ease-in-out, transform 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1E3E26;\n"
"    transform: scale(1.05);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #153021;\n"
"    transform: scale(0.95);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\PycharmProjects\\K24406H\\DO_AN_NHOM_KTLT\\ui\\../images/ic_login.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogin.setIcon(icon)
        self.pushButtonLogin.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #2E5636; /* Xanh lá đậm hơn */\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: #2E5636; /* Xanh lá đậm hơn */\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditUsername.setGeometry(QtCore.QRect(100, 140, 201, 31))
        self.lineEditUsername.setMouseTracking(True)
        self.lineEditUsername.setTabletTracking(False)
        self.lineEditUsername.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.lineEditUsername.setAutoFillBackground(False)
        self.lineEditUsername.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0.8); /* Nền trắng rõ hơn */\n"
"    border: 2px solid rgba(255, 255, 255, 1); /* Viền trắng đậm */\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-size: 12px;\n"
"    color: black;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgba(0, 0, 0, 0.7); /* Viền đen khi nhập */\n"
"    background-color: rgba(255, 255, 255, 1); /* Sáng hơn khi nhập */\n"
"}\n"
"\n"
"")
        self.lineEditUsername.setText("")
        self.lineEditUsername.setFrame(True)
        self.lineEditUsername.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditUsername.setDragEnabled(False)
        self.lineEditUsername.setReadOnly(False)
        self.lineEditUsername.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEditUsername.setClearButtonEnabled(False)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 250, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    color: #2E5636; /* Xanh lá đậm hơn */\n"
"    background: transparent;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonExit.setGeometry(QtCore.QRect(190, 300, 114, 41))
        self.pushButtonExit.setStyleSheet("QPushButton {\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-size: 14px; /* Giảm size chữ */\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: #2E5636;\n"
"    border: 2px solid #1E3E26;\n"
"    border-radius: 12px; /* Giảm độ bo góc */\n"
"    padding: 5px 15px; /* Giảm padding để nút nhỏ hơn */\n"
"    min-width: 80px; /* Giảm kích thước tối thiểu của nút */\n"
"    transition: background 0.3s ease-in-out, transform 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1E3E26;\n"
"    transform: scale(1.05);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #153021;\n"
"    transform: scale(0.95);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("E:\\PycharmProjects\\K24406H\\DO_AN_NHOM_KTLT\\ui\\../images/ic_exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon1)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(100, 80, 151, 41))
        self.label.setStyleSheet("QLabel {\n"
"    color: #2E5636; /* Xanh lá đậm hơn */\n"
"    background: transparent;\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(90, 20, 171, 51))
        self.label_4.setStyleSheet("QLabel {\n"
"    color: #2E5636; /* Xanh lá đậm hơn */\n"
"    background: transparent;\n"
"    font-size: 20px;\n"
"    font-weight: normal;\n"
"    letter-spacing: 1px;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditUsername, self.lineEditPassword)
        MainWindow.setTabOrder(self.lineEditPassword, self.pushButtonLogin)
        MainWindow.setTabOrder(self.pushButtonLogin, self.pushButtonExit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LoginMainWindow"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Username:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Password:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Forget your Username or Password?"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.label_4.setText(_translate("MainWindow", "Welcome Back"))
