# Form implementation generated from reading ui file 'E:\PycharmProjects\K24406H\DO_AN_NHOM_KTLT\ui\MainWindowAdmin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5dc; /* Be nhạt */\n"
"}\n"
"QWidget {\n"
"    background-color: #f8f1e4; /* Be sáng hơn một chút */\n"
"}\n"
"/* Chỉnh tiêu đề chính \"Thông Tin Phòng\" */\n"
"QLabel#label_Title {\n"
"    color: #1B4332;  /* Xanh lá đậm nổi bật */\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Chỉnh màu chữ trong phần \"Thông tin quản lý\" */\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #2D6A4F;  /* Xanh đậm hơn */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Chỉnh màu cho QPushButton */\n"
"QPushButton {\n"
"    background-color: #FFB703; /* Cam nhạt để hợp với xanh lá */\n"
"    color: white;\n"
"    font-size: 16px;  /* Tăng kích thước chữ */\n"
"    font-weight: bold;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E85D04; /* Cam đậm khi hover */\n"
"}\n"
"\n"
"/* Chỉnh màu nút \"Đăng xuất\" */\n"
"QPushButton#pushButton_Logout {\n"
"    background-color: #D00000;  /* Đỏ đậm để nổi bật */\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_Logout:hover {\n"
"    background-color: #9D0208;\n"
"}\n"
"\n"
"/* Chỉnh màu cho ô tìm kiếm */\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #1B4332;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* Chỉnh màu cho QTableWidget */\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 2px solid #1B4332; \n"
"    gridline-color: #1B4332;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #95D5B2;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    border: 1px solid #1B4332;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #C0C0C0; /* Màu nền khi hover */\n"
"    color: black; /* Màu chữ khi hover */\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 0, 1411, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"QLabel {\n"
"    font-family: \'Montserrat\', sans-serif;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    color: rgb(0, 85, 0); \n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.groupBoxRoom = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxRoom.setGeometry(QtCore.QRect(50, 110, 671, 291))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBoxRoom.setFont(font)
        self.groupBoxRoom.setObjectName("groupBoxRoom")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxRoom)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidgetRoom = QtWidgets.QTableWidget(parent=self.groupBoxRoom)
        self.tableWidgetRoom.setObjectName("tableWidgetRoom")
        self.tableWidgetRoom.setColumnCount(6)
        self.tableWidgetRoom.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRoom.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRoom.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRoom.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRoom.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRoom.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRoom.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.tableWidgetRoom)
        self.groupBoxCustomer = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxCustomer.setGeometry(QtCore.QRect(50, 460, 671, 301))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBoxCustomer.setFont(font)
        self.groupBoxCustomer.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.groupBoxCustomer.setObjectName("groupBoxCustomer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxCustomer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidgetCustomer = QtWidgets.QTableWidget(parent=self.groupBoxCustomer)
        self.tableWidgetCustomer.setObjectName("tableWidgetCustomer")
        self.tableWidgetCustomer.setColumnCount(6)
        self.tableWidgetCustomer.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.tableWidgetCustomer)
        self.groupBoxInformation = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxInformation.setGeometry(QtCore.QRect(900, 90, 561, 411))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBoxInformation.setFont(font)
        self.groupBoxInformation.setStyleSheet("#groupBoxInformation {\n"
"    background: rgba(255, 255, 255, 0.2);  /* Màu trắng trong suốt */\n"
"    border-radius: 10px;  /* Bo góc */\n"
"    border: 1px solid rgba(255, 255, 255, 0.4); /* Viền trắng mờ */\n"
"    backdrop-filter: blur(10px);  /* Hiệu ứng làm mờ */\n"
"}")
        self.groupBoxInformation.setObjectName("groupBoxInformation")
        self.lineEditRoomID = QtWidgets.QLineEdit(parent=self.groupBoxInformation)
        self.lineEditRoomID.setGeometry(QtCore.QRect(180, 40, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditRoomID.setFont(font)
        self.lineEditRoomID.setObjectName("lineEditRoomID")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBoxInformation)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEditTypeRoom = QtWidgets.QLineEdit(parent=self.groupBoxInformation)
        self.lineEditTypeRoom.setGeometry(QtCore.QRect(180, 80, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditTypeRoom.setFont(font)
        self.lineEditTypeRoom.setObjectName("lineEditTypeRoom")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBoxInformation)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEditStatus = QtWidgets.QLineEdit(parent=self.groupBoxInformation)
        self.lineEditStatus.setGeometry(QtCore.QRect(180, 120, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditStatus.setFont(font)
        self.lineEditStatus.setObjectName("lineEditStatus")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBoxInformation)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEditFloor = QtWidgets.QLineEdit(parent=self.groupBoxInformation)
        self.lineEditFloor.setGeometry(QtCore.QRect(180, 160, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditFloor.setFont(font)
        self.lineEditFloor.setObjectName("lineEditFloor")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBoxInformation)
        self.label_12.setGeometry(QtCore.QRect(10, 200, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBoxInformation)
        self.label_7.setGeometry(QtCore.QRect(10, 240, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEditName = QtWidgets.QLineEdit(parent=self.groupBoxInformation)
        self.lineEditName.setGeometry(QtCore.QRect(180, 240, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditName.setFont(font)
        self.lineEditName.setObjectName("lineEditName")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBoxInformation)
        self.label_13.setGeometry(QtCore.QRect(10, 280, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.groupBoxInformation)
        self.lineEditPhone.setGeometry(QtCore.QRect(180, 280, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditPhone.setFont(font)
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBoxInformation)
        self.label_11.setGeometry(QtCore.QRect(10, 320, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEditCCCD = QtWidgets.QLineEdit(parent=self.groupBoxInformation)
        self.lineEditCCCD.setGeometry(QtCore.QRect(180, 320, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditCCCD.setFont(font)
        self.lineEditCCCD.setObjectName("lineEditCCCD")
        self.lineEditCustomerID = QtWidgets.QLineEdit(parent=self.groupBoxInformation)
        self.lineEditCustomerID.setGeometry(QtCore.QRect(180, 200, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditCustomerID.setFont(font)
        self.lineEditCustomerID.setObjectName("lineEditCustomerID")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBoxInformation)
        self.label_9.setGeometry(QtCore.QRect(10, 360, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEditDateCheckin = QtWidgets.QLineEdit(parent=self.groupBoxInformation)
        self.lineEditDateCheckin.setGeometry(QtCore.QRect(180, 360, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditDateCheckin.setFont(font)
        self.lineEditDateCheckin.setObjectName("lineEditDateCheckin")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBoxInformation)
        self.label_10.setGeometry(QtCore.QRect(10, 40, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.groupBoxFunction = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxFunction.setGeometry(QtCore.QRect(900, 520, 561, 211))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBoxFunction.setFont(font)
        self.groupBoxFunction.setStyleSheet("#groupBoxFunction {\n"
"    background: rgba(255, 255, 255, 0.2);  /* Màu trắng trong suốt */\n"
"    border-radius: 10px;  /* Bo góc */\n"
"    border: 1px solid rgba(255, 255, 255, 0.4); /* Viền trắng mờ */\n"
"    backdrop-filter: blur(10px);  /* Hiệu ứng làm mờ */\n"
"}")
        self.groupBoxFunction.setObjectName("groupBoxFunction")
        self.pushButtonXoa = QtWidgets.QPushButton(parent=self.groupBoxFunction)
        self.pushButtonXoa.setGeometry(QtCore.QRect(280, 40, 231, 51))
        self.pushButtonXoa.setStyleSheet("QPushButton {\n"
"    background-color: #f5deb3; /* Màu be */\n"
"    color: #4A4A4A;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"    border: 2px solid #d2b48c; /* Viền be đậm hơn */\n"
"    transition: 0.3s ease-in-out;\n"
"}\n"
"\n"
"/* Hiệu ứng hover */\n"
"QPushButton:hover {\n"
"    background-color: #e3c193; /* Be đậm hơn khi hover */\n"
"    transform: scale(1.05);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\PycharmProjects\\K24406H\\DO_AN_NHOM_KTLT\\ui\\../images/remove.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonXoa.setIcon(icon)
        self.pushButtonXoa.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonXoa.setObjectName("pushButtonXoa")
        self.pushButtonHoaDon = QtWidgets.QPushButton(parent=self.groupBoxFunction)
        self.pushButtonHoaDon.setGeometry(QtCore.QRect(280, 120, 231, 51))
        self.pushButtonHoaDon.setStyleSheet("QPushButton {\n"
"    background-color: #f5deb3; /* Màu be */\n"
"    color: #4A4A4A;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"    border: 2px solid #d2b48c; /* Viền be đậm hơn */\n"
"    transition: 0.3s ease-in-out;\n"
"}\n"
"\n"
"/* Hiệu ứng hover */\n"
"QPushButton:hover {\n"
"    background-color: #e3c193; /* Be đậm hơn khi hover */\n"
"    transform: scale(1.05);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("E:\\PycharmProjects\\K24406H\\DO_AN_NHOM_KTLT\\ui\\../images/bill.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonHoaDon.setIcon(icon1)
        self.pushButtonHoaDon.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonHoaDon.setObjectName("pushButtonHoaDon")
        self.pushButtonDatPhong = QtWidgets.QPushButton(parent=self.groupBoxFunction)
        self.pushButtonDatPhong.setGeometry(QtCore.QRect(10, 120, 231, 51))
        self.pushButtonDatPhong.setStyleSheet("QPushButton {\n"
"    background-color: #f5deb3; /* Màu be */\n"
"    color: #4A4A4A;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"    border: 2px solid #d2b48c; /* Viền be đậm hơn */\n"
"    transition: 0.3s ease-in-out;\n"
"}\n"
"\n"
"/* Hiệu ứng hover */\n"
"QPushButton:hover {\n"
"    background-color: #e3c193; /* Be đậm hơn khi hover */\n"
"    transform: scale(1.05);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("E:\\PycharmProjects\\K24406H\\DO_AN_NHOM_KTLT\\ui\\../images/booking.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonDatPhong.setIcon(icon2)
        self.pushButtonDatPhong.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonDatPhong.setObjectName("pushButtonDatPhong")
        self.pushButtonSua = QtWidgets.QPushButton(parent=self.groupBoxFunction)
        self.pushButtonSua.setGeometry(QtCore.QRect(10, 40, 231, 51))
        self.pushButtonSua.setStyleSheet("QPushButton {\n"
"    background-color: #f5deb3; /* Màu be */\n"
"    color: #4A4A4A;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"    border: 2px solid #d2b48c; /* Viền be đậm hơn */\n"
"    transition: 0.3s ease-in-out;\n"
"}\n"
"\n"
"/* Hiệu ứng hover */\n"
"QPushButton:hover {\n"
"    background-color: #e3c193; /* Be đậm hơn khi hover */\n"
"    transform: scale(1.05);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("E:\\PycharmProjects\\K24406H\\DO_AN_NHOM_KTLT\\ui\\../images/edit.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSua.setIcon(icon3)
        self.pushButtonSua.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonSua.setObjectName("pushButtonSua")
        self.pushButtonLogout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogout.setGeometry(QtCore.QRect(1410, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLogout.setFont(font)
        self.pushButtonLogout.setStyleSheet("background-color: rgb(85, 170, 127);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("E:\\PycharmProjects\\K24406H\\DO_AN_NHOM_KTLT\\ui\\../images/logout.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogout.setIcon(icon4)
        self.pushButtonLogout.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonLogout.setObjectName("pushButtonLogout")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditSeachCustomer = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditSeachCustomer.setGeometry(QtCore.QRect(160, 420, 551, 31))
        self.lineEditSeachCustomer.setObjectName("lineEditSeachCustomer")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 420, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEditSeachRoom = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditSeachRoom.setGeometry(QtCore.QRect(160, 70, 551, 31))
        self.lineEditSeachRoom.setObjectName("lineEditSeachRoom")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 21))
        self.menubar.setObjectName("menubar")
        self.menuSystem = QtWidgets.QMenu(parent=self.menubar)
        self.menuSystem.setObjectName("menuSystem")
        self.menuImport_Data = QtWidgets.QMenu(parent=self.menuSystem)
        self.menuImport_Data.setStyleSheet("")
        self.menuImport_Data.setObjectName("menuImport_Data")
        self.menuExport_Data = QtWidgets.QMenu(parent=self.menuSystem)
        self.menuExport_Data.setObjectName("menuExport_Data")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExcel_Import = QtGui.QAction(parent=MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("E:\\PycharmProjects\\K24406H\\DO_AN_NHOM_KTLT\\ui\\../images/ic_excel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExcel_Import.setIcon(icon5)
        self.actionExcel_Import.setObjectName("actionExcel_Import")
        self.actionExcel_Export = QtGui.QAction(parent=MainWindow)
        self.actionExcel_Export.setIcon(icon5)
        self.actionExcel_Export.setObjectName("actionExcel_Export")
        self.actionHelp = QtGui.QAction(parent=MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("E:\\PycharmProjects\\K24406H\\DO_AN_NHOM_KTLT\\ui\\../images/ic_help.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionHelp.setIcon(icon6)
        self.actionHelp.setObjectName("actionHelp")
        self.menuImport_Data.addAction(self.actionExcel_Import)
        self.menuExport_Data.addAction(self.actionExcel_Export)
        self.menuSystem.addAction(self.menuImport_Data.menuAction())
        self.menuSystem.addSeparator()
        self.menuSystem.addAction(self.menuExport_Data.menuAction())
        self.menuSystem.addSeparator()
        self.menuSystem.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuSystem.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindowAdmin"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">QUẢN LÝ KHÁCH SẠN</span></p></body></html>"))
        self.groupBoxRoom.setTitle(_translate("MainWindow", "Danh sách phòng:"))
        item = self.tableWidgetRoom.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID Phòng"))
        item = self.tableWidgetRoom.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Loại phòng"))
        item = self.tableWidgetRoom.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Giá/giờ"))
        item = self.tableWidgetRoom.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Giá/ngày"))
        item = self.tableWidgetRoom.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Trạng thái"))
        item = self.tableWidgetRoom.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Tầng"))
        self.groupBoxCustomer.setTitle(_translate("MainWindow", "Danh sách khách hàng:"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SĐT"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CCCD"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Mã phòng"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Ngày nhận phòng"))
        self.groupBoxInformation.setTitle(_translate("MainWindow", "Thông tin quản lý:"))
        self.label_4.setText(_translate("MainWindow", "Loại phòng:"))
        self.label_5.setText(_translate("MainWindow", "Trạng thái:"))
        self.label_6.setText(_translate("MainWindow", "Tầng:"))
        self.label_12.setText(_translate("MainWindow", "STT Khách hàng:"))
        self.label_7.setText(_translate("MainWindow", "Tên khách hàng:"))
        self.label_13.setText(_translate("MainWindow", "SĐT:"))
        self.label_11.setText(_translate("MainWindow", "CCCD:"))
        self.label_9.setText(_translate("MainWindow", "Ngày nhận phòng:"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">STT phòng:</span></p></body></html>"))
        self.groupBoxFunction.setTitle(_translate("MainWindow", "Chức năng:"))
        self.pushButtonXoa.setText(_translate("MainWindow", "Xóa"))
        self.pushButtonHoaDon.setText(_translate("MainWindow", "Tạo hóa đơn"))
        self.pushButtonDatPhong.setText(_translate("MainWindow", "Đặt phòng"))
        self.pushButtonSua.setText(_translate("MainWindow", "Sửa"))
        self.pushButtonLogout.setText(_translate("MainWindow", "Đăng xuất"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Tìm kiếm:</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Tìm kiếm:</span></p></body></html>"))
        self.menuSystem.setTitle(_translate("MainWindow", "System"))
        self.menuImport_Data.setTitle(_translate("MainWindow", "Import Data"))
        self.menuExport_Data.setTitle(_translate("MainWindow", "Export Data"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Esc"))
        self.actionExcel_Import.setText(_translate("MainWindow", "Excel File"))
        self.actionExcel_Import.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionExcel_Export.setText(_translate("MainWindow", "Excel File"))
        self.actionExcel_Export.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionHelp.setText(_translate("MainWindow", "Current Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1"))
