# Form implementation generated from reading ui file 'E:\PycharmProjects\K24406H\DO_AN_NHOM_KTLT\ui\PayBillMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 713)
        font = QtGui.QFont()
        font.setItalic(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f5f5dc; /* Be nhạt */\n"
"}\n"
"QWidget {\n"
"    background-color: #f8f1e4; /* Be sáng hơn một chút */\n"
"}\n"
"/* Chỉnh màu chữ trong phần \"Thông tin quản lý\" */\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #2D6A4F;  /* Xanh đậm hơn */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Chỉnh màu cho QPushButton */\n"
"QPushButton {\n"
"    background-color: #FFB703; /* Cam nhạt để hợp với xanh lá */\n"
"    color: white;\n"
"    font-size: 16px;  /* Tăng kích thước chữ */\n"
"    font-weight: bold;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E85D04; /* Cam đậm khi hover */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #95D5B2;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    border: 1px solid #1B4332;\n"
"}\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #1B4332;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 13px;\n"
"}\n"
"QDateTimeEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #1B4332;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: white;\n"
"    border: 2px solid #1B4332;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 0, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    font-family: \'Montserrat\', sans-serif;\n"
"    font-size: 26px;\n"
"    font-weight: bold;\n"
"    color: rgb(0, 85, 0); \n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 50, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditbillId = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditbillId.setGeometry(QtCore.QRect(360, 60, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditbillId.setFont(font)
        self.lineEditbillId.setObjectName("lineEditbillId")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 130, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEditname = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditname.setGeometry(QtCore.QRect(310, 150, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditname.setFont(font)
        self.lineEditname.setObjectName("lineEditname")
        self.lineEditroomId = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditroomId.setGeometry(QtCore.QRect(310, 190, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditroomId.setFont(font)
        self.lineEditroomId.setObjectName("lineEditroomId")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 170, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 220, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 260, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 300, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.dateTimeEditcheckin = QtWidgets.QDateTimeEdit(parent=self.centralwidget)
        self.dateTimeEditcheckin.setGeometry(QtCore.QRect(310, 270, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.dateTimeEditcheckin.setFont(font)
        self.dateTimeEditcheckin.setObjectName("dateTimeEditcheckin")
        self.dateTimeEditcheckout = QtWidgets.QDateTimeEdit(parent=self.centralwidget)
        self.dateTimeEditcheckout.setGeometry(QtCore.QRect(310, 310, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.dateTimeEditcheckout.setFont(font)
        self.dateTimeEditcheckout.setObjectName("dateTimeEditcheckout")
        self.lineEditprice = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditprice.setGeometry(QtCore.QRect(310, 430, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditprice.setFont(font)
        self.lineEditprice.setObjectName("lineEditprice")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 420, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 500, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEditphuthu = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditphuthu.setGeometry(QtCore.QRect(310, 470, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditphuthu.setFont(font)
        self.lineEditphuthu.setObjectName("lineEditphuthu")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(70, 460, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.cbphuongthuc = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbphuongthuc.setGeometry(QtCore.QRect(310, 510, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.cbphuongthuc.setFont(font)
        self.cbphuongthuc.setObjectName("cbphuongthuc")
        self.cbphuongthuc.addItem("")
        self.cbphuongthuc.addItem("")
        self.cbphuongthuc.addItem("")
        self.lineEdittongtien = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdittongtien.setGeometry(QtCore.QRect(310, 550, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdittongtien.setFont(font)
        self.lineEdittongtien.setObjectName("lineEdittongtien")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(70, 550, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.pushButtonthoat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonthoat.setGeometry(QtCore.QRect(470, 610, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonthoat.setFont(font)
        self.pushButtonthoat.setStyleSheet("QPushButton {\n"
"    background-color: #f5deb3; /* Màu be */\n"
"    color: #4A4A4A;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"    border: 2px solid #d2b48c; /* Viền be đậm hơn */\n"
"    transition: 0.3s ease-in-out;\n"
"}\n"
"\n"
"/* Hiệu ứng hover */\n"
"QPushButton:hover {\n"
"    background-color: #e3c193; /* Be đậm hơn khi hover */\n"
"    transform: scale(1.05);\n"
"}")
        self.pushButtonthoat.setObjectName("pushButtonthoat")
        self.lineEditroom_type = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditroom_type.setGeometry(QtCore.QRect(310, 230, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditroom_type.setFont(font)
        self.lineEditroom_type.setObjectName("lineEditroom_type")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(70, 340, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdittime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdittime.setGeometry(QtCore.QRect(310, 350, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdittime.setFont(font)
        self.lineEdittime.setObjectName("lineEdittime")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(70, 380, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEditrent_price = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditrent_price.setGeometry(QtCore.QRect(310, 390, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditrent_price.setFont(font)
        self.lineEditrent_price.setObjectName("lineEditrent_price")
        self.pushButtonxacnhan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonxacnhan.setGeometry(QtCore.QRect(110, 610, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonxacnhan.setFont(font)
        self.pushButtonxacnhan.setStyleSheet("QPushButton {\n"
"    background-color: #f5deb3; /* Màu be */\n"
"    color: #4A4A4A;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"    border: 2px solid #d2b48c; /* Viền be đậm hơn */\n"
"    transition: 0.3s ease-in-out;\n"
"}\n"
"\n"
"/* Hiệu ứng hover */\n"
"QPushButton:hover {\n"
"    background-color: #e3c193; /* Be đậm hơn khi hover */\n"
"    transform: scale(1.05);\n"
"}")
        self.pushButtonxacnhan.setObjectName("pushButtonxacnhan")
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(70, 100, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.lineEditcustomerId = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditcustomerId.setGeometry(QtCore.QRect(310, 110, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditcustomerId.setFont(font)
        self.lineEditcustomerId.setObjectName("lineEditcustomerId")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(610, 40, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Thanh toán hóa đơn"))
        self.label.setText(_translate("MainWindow", "HÓA ĐƠN THANH TOÁN"))
        self.label_2.setText(_translate("MainWindow", "SỐ HĐ:"))
        self.label_3.setText(_translate("MainWindow", "Tên khách hàng:"))
        self.label_4.setText(_translate("MainWindow", "Phòng:"))
        self.label_5.setText(_translate("MainWindow", "Loại phòng:"))
        self.label_6.setText(_translate("MainWindow", "Ngày nhận phòng:"))
        self.label_7.setText(_translate("MainWindow", "Ngày trả phòng:"))
        self.label_8.setText(_translate("MainWindow", "Thành tiền:"))
        self.label_9.setText(_translate("MainWindow", "Phương thức thanh toán:"))
        self.label_10.setText(_translate("MainWindow", "Phụ thu:"))
        self.cbphuongthuc.setItemText(0, _translate("MainWindow", "Tiền mặt"))
        self.cbphuongthuc.setItemText(1, _translate("MainWindow", "Chuyển khoản"))
        self.cbphuongthuc.setItemText(2, _translate("MainWindow", "Thẻ tín dụng"))
        self.label_11.setText(_translate("MainWindow", "Tổng tiền:"))
        self.pushButtonthoat.setText(_translate("MainWindow", "THOÁT"))
        self.label_12.setText(_translate("MainWindow", "Thời gian lưu trú:"))
        self.label_13.setText(_translate("MainWindow", "Đơn giá:"))
        self.pushButtonxacnhan.setText(_translate("MainWindow", "XÁC NHẬN THANH TOÁN"))
        self.label_14.setText(_translate("MainWindow", "Mã khách hàng:"))
        self.label_15.setText(_translate("MainWindow", "Đơn vị: VNĐ"))
